import os
import subprocess
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from methods.runtime_evaluator.graph import build_observed_source_graph, write_observed_source_graph  # noqa: E402
from modash import compile_observed_main  # noqa: E402
from test.support import ScriptProject  # noqa: E402


class RuntimeObservedCompilerTestCase(unittest.TestCase):
    def _compile_from_trace(self, project, entry="main.sh", *, argv=(), env=None):
        trace = project.trace(entry, argv=argv, env=env)
        self.assertEqual(trace.returncode, 0, trace.stderr)
        graph = build_observed_source_graph(project.path(entry), trace.observation)
        graph_path = project.path("graph/runtime-source-graph.json")
        compiled = project.path("compiled.sh")
        write_observed_source_graph(graph, graph_path)
        compile_observed_main(str(project.path(entry)), str(compiled), graph=str(graph_path))
        return compiled

    def _bash(self, script, project, *, argv=(), env=None):
        merged = os.environ.copy()
        if env:
            merged.update({str(key): str(value) for key, value in env.items()})
        script_path = project.path(script)
        command = [str(script_path), *argv] if os.access(script_path, os.X_OK) else ["bash", str(script_path), *argv]
        return subprocess.run(
            command,
            cwd=project.root,
            env=merged,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10,
        )

    def test_runtime_compiler_preserves_no_arg_positionals_and_source_return(self):
        with ScriptProject() as project:
            positional_dep = project.write(
                "positional.sh",
                'printf "dep-pos:%s:%s\\n" "${1-unset}" "${2-unset}"\n',
            )
            return_dep = project.write(
                "return.sh",
                'printf "dep-return:%s:%s:%s\\n" "${1-unset}" "${2-unset}" "${3-unset}"\n'
                'return 7\n'
                'printf "unreachable\\n"\n',
            )
            project.write(
                "main.sh",
                'source "$DEP_POSITIONAL"\n'
                'printf "main:%s:%s\\n" "${1-unset}" "${2-unset}"\n'
                'if source "$DEP_RETURN" X Y; then printf "ok\\n"; else printf "return:%s\\n" "$?"; fi\n',
            )
            env = {"DEP_POSITIONAL": str(positional_dep), "DEP_RETURN": str(return_dep)}
            compiled = self._compile_from_trace(project, argv=("A", "B"), env=env)
            expected = self._bash("main.sh", project, argv=("A", "B"), env=env)
            actual = self._bash(compiled, project, argv=("A", "B"), env=env)
            compiled_text = compiled.read_text()

        self.assertEqual(actual.returncode, expected.returncode, actual.stderr)
        self.assertEqual(actual.stdout, expected.stdout)
        self.assertEqual(actual.stderr, expected.stderr)
        self.assertIn("Generated by modash 0.7 trusted runtime graph compiler", compiled_text)

    def test_runtime_compiler_preserves_explicit_source_argument_scope(self):
        with ScriptProject() as project:
            project.write(
                "main.sh",
                'set -- caller original\n'
                'source ./dep.sh observed args\n'
                'printf "main:%s:%s:%s\\n" "${1-unset}" "${2-unset}" "${3-unset}"\n',
            )
            project.write(
                "dep.sh",
                'printf "dep:%s:%s:%s\\n" "${1-unset}" "${2-unset}" "${3-unset}"\n'
                'shift\n'
                'printf "dep-after-shift:%s:%s:%s\\n" "${1-unset}" "${2-unset}" "${3-unset}"\n',
            )
            compiled = self._compile_from_trace(project)
            expected = self._bash("main.sh", project)
            actual = self._bash(compiled, project)

        self.assertEqual(actual.returncode, expected.returncode, actual.stderr)
        self.assertEqual(actual.stdout, expected.stdout)
        self.assertEqual(actual.stderr, expected.stderr)

    def test_runtime_compiler_fails_closed_when_unobserved_source_branch_runs(self):
        with ScriptProject() as project:
            project.write(
                "main.sh",
                'if [[ ${LOAD_DEP:-no} == yes ]]; then source ./dep.sh; fi\n'
                'printf "done:%s\\n" "${VALUE-unset}"\n',
            )
            project.write("dep.sh", 'VALUE=loaded\nprintf "dep\\n"\n')
            compiled = self._compile_from_trace(project)
            observed = self._bash(compiled, project)
            unobserved = self._bash(compiled, project, env={"LOAD_DEP": "yes"})

        self.assertEqual(observed.returncode, 0, observed.stderr)
        self.assertEqual(observed.stdout, "done:unset\n")
        self.assertEqual(unobserved.returncode, 125, unobserved.stderr)
        self.assertIn("modash runtime replay error: unobserved or over-consumed source edge", unobserved.stderr)

    def test_same_relative_identical_helpers_replay_by_observed_site(self):
        with ScriptProject() as project:
            project.write(
                "main.sh",
                'cd one\n'
                'source ./helpers.sh\n'
                'load_dep\n'
                'cd ../two\n'
                'source ./helpers.sh\n'
                'load_dep\n',
            )
            for directory, value in (("one", "one"), ("two", "two")):
                project.write(f"{directory}/helpers.sh", 'load_dep() { source ./dep.sh; }\n')
                project.write(f"{directory}/dep.sh", f'printf "dep:{value}\\n"\n')
            compiled = self._compile_from_trace(project)
            expected = self._bash("main.sh", project)
            actual = self._bash(compiled, project)

        self.assertEqual(actual.returncode, expected.returncode, actual.stderr)
        self.assertEqual(actual.stdout, expected.stdout)
        self.assertEqual(actual.stderr, expected.stderr)


if __name__ == "__main__":
    unittest.main()
