from __future__ import annotations

import base64
import re
import shutil
import shlex
from pathlib import Path

from methods.runtime_evaluator.compiler_model import (
    ENTRYPOINT_LOGICAL_PATH,
    REPLAY_FAILURE_STATUS,
    RuntimeObservedCompileError,
    _EmbeddedFile,
    _ReplayEdge,
    _RewriteUnit,
    _first_source_segment,
    _validate_logical_path,
)
from methods.source_commands import source_command_invocation

RUNTIME_REPLAY_SHEBANG = "#!/bin/bash -p"


def _render_replay_prelude(
    embedded_files: tuple[_EmbeddedFile, ...],
    assignments: dict[str, list[_ReplayEdge]],
    target_logical_paths: dict[str, str],
    environment_values: dict[str, str] | None = None,
    child_processes: tuple[int, ...] = (),
) -> str:
    bash_path = _required_tool("bash")
    mktemp_path = _required_tool("mktemp")
    mkdir_path = _required_tool("mkdir")
    base64_path = _required_tool("base64")
    rm_path = _required_tool("rm")
    kill_path = _required_tool("kill")
    printf_path = _required_tool("printf")

    payload_setup = []
    for file in embedded_files:
        _validate_logical_path(file.logical_path)
        encoded = base64.b64encode(file.content.encode("utf-8")).decode("ascii")
        payload_setup.append(f"__modash_embedded_payload[{shlex.quote(file.logical_path)}]={shlex.quote(encoded)}")

    map_setup: list[str] = []
    edge_keys: list[str] = []
    for base_id, edges in sorted(assignments.items()):
        for occurrence, edge in enumerate(edges):
            key = f"{base_id}|{occurrence}"
            edge_keys.append(key)
            map_setup.extend(_edge_map_lines(base_id, occurrence, edge, target_logical_paths))
    process_keys = [f"{process_index}|0" for process_index in sorted(child_processes)]
    edge_verify = "\n".join(_verify_consumed_lines("__modash_edge_consumed", "source edge", edge_keys))
    process_verify = "\n".join(_verify_consumed_lines("__modash_process_consumed", "child process", process_keys))
    environment_verify = "\n".join(_environment_verify_lines(environment_values or {}))

    return f'''{RUNTIME_REPLAY_SHEBANG}
# Generated by modash 0.7 trusted runtime graph compiler.

if [[ $- != *p* ]]; then
  {shlex.quote(printf_path)} 'modash runtime graph output must be executed directly or with bash -p\n' >&2
  {shlex.quote(kill_path)} -KILL "$$" 2>/dev/null
  exit {REPLAY_FAILURE_STATUS}
fi

__modash_bash={shlex.quote(bash_path)}
__modash_mktemp={shlex.quote(mktemp_path)}
__modash_mkdir={shlex.quote(mkdir_path)}
__modash_base64={shlex.quote(base64_path)}
__modash_rm={shlex.quote(rm_path)}
__modash_kill={shlex.quote(kill_path)}

unset BASH_ENV

__modash_tmp=$("$__modash_mktemp" -d "${{TMPDIR:-/tmp}}/modash-runtime.XXXXXX") || builtin exit {REPLAY_FAILURE_STATUS}
readonly __modash_bash __modash_mktemp __modash_mkdir __modash_base64 __modash_rm __modash_kill __modash_tmp

__modash_abort() {{
  builtin printf 'modash runtime replay error: %s\\n' "$1" >&2
  if [[ ${{BASHPID:-$$}} != $$ ]]; then
    builtin printf '%s\\n' "$1" > "$__modash_tmp/replay-failure" 2>/dev/null || :
    builtin exit {REPLAY_FAILURE_STATUS}
  fi
  "$__modash_rm" -rf -- "$__modash_tmp"
  builtin trap - EXIT
  builtin exit {REPLAY_FAILURE_STATUS}
}}

{environment_verify}

declare -A __modash_embedded_payload=()
{chr(10).join(payload_setup)}
readonly -A __modash_embedded_payload
__modash_materialized_embedded_index=0

__modash_emit_embedded_file() {{
  local logical_path=$1 encoded
  [[ ${{__modash_embedded_payload[$logical_path]+set}} == set ]] || __modash_abort "missing embedded payload: $logical_path"
  encoded=${{__modash_embedded_payload[$logical_path]}}
  builtin printf '%s' "$encoded" | "$__modash_base64" -d || __modash_abort "could not decode embedded file: $logical_path"
}}

__modash_materialize_embedded_file() {{
  local logical_path=$1 path
  __modash_require_embedded_file "$logical_path"
  path="$__modash_tmp/embedded-${{__modash_materialized_embedded_index}}.sh"
  __modash_materialized_embedded_index=$((__modash_materialized_embedded_index + 1))
  __modash_emit_embedded_file "$logical_path" > "$path" || __modash_abort "could not materialize embedded file: $logical_path"
  builtin printf '%s' "$path"
}}

__modash_require_embedded_file() {{
  local logical_path=$1
  [[ ${{__modash_embedded_payload[$logical_path]+set}} == set ]] || __modash_abort "missing embedded payload: $logical_path"
}}

__modash_physical_pwd() {{
  builtin pwd -P 2>/dev/null || builtin printf '%s' "$PWD"
}}

__modash_eval_shopt_restore() {{
  local script=$1 line flag option
  while IFS= read -r line || [[ -n $line ]]; do
    [[ $line =~ ^[[:space:]]*shopt[[:space:]]+(-[su])[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*$ ]] || __modash_abort "unsafe shopt restore eval"
    flag=${{BASH_REMATCH[1]}}
    option=${{BASH_REMATCH[2]}}
    builtin shopt "$flag" "$option" || __modash_abort "failed shopt restore"
  done <<< "$script"
}}

__modash_literal_eval_argument_is_safe() {{
  local argument=$1
  [[ $argument =~ ^\\$\\{{[A-Za-z_][A-Za-z0-9_]*\\}}$ ]] && return 0
  case "$argument" in
    *'$'*|*'`'*|*';'*|*'&'*|*'|'*|*'<'*|*'>'*|*'('*|*')'*)
      return 1
      ;;
  esac
  return 0
}}

eval() {{
  local command=${{1-}} argument
  if (( $# == 0 )); then
    builtin eval
    return
  fi
  case "$command" in
    echo|:)
      shift
      for argument in "$@"; do
        __modash_literal_eval_argument_is_safe "$argument" || __modash_abort "unsafe literal eval argument"
      done
      builtin eval "$command" "$@"
      ;;
    *)
      __modash_abort "runtime replay cannot allow live eval"
      ;;
  esac
}}

__modash_word_contains_source_payload() {{
  case "$1" in
    *"source "*|*" source"*|*". "*|*" ."*|*"builtin source"*|*"command source"*|*"builtin ."*|*"command ."*|*'__modash_'*|*'__entrypoint__'*|*'__process_command__'*)
      return 0
      ;;
  esac
  return 1
}}

__modash_guard_dynamic_command() {{
  local command=${{1-}} word skip_next=0 saw_shell_c=0
  case "$command" in
    source|.|eval|exec|trap|enable)
      case "$command" in
        source|.)
          __modash_abort "unobserved live source command: $command"
          ;;
        eval)
          __modash_abort "runtime replay cannot allow live eval"
          ;;
        exec)
          __modash_abort "runtime replay cannot allow live exec"
          ;;
        trap)
          __modash_abort "runtime replay cannot allow live trap"
          ;;
        *)
          __modash_abort "runtime replay cannot allow dynamic replay-critical command: $command"
          ;;
      esac
      ;;
    command|builtin)
      shift
      while (( $# )); do
        case "$1" in
          --)
            shift
            break
            ;;
          -p)
            shift
            continue
            ;;
          -*)
            __modash_abort "runtime replay cannot allow dynamic command wrapper options"
            ;;
          *)
            break
            ;;
        esac
      done
      (( $# == 0 )) && __modash_abort "runtime replay cannot allow empty dynamic command wrapper"
      __modash_guard_dynamic_command "$@"
      return
      ;;
    printf)
      shift
      while (( $# )); do
        if [[ $1 == -v ]]; then
          shift
          (( $# )) || __modash_abort "runtime replay cannot allow dynamic printf -v without target"
          __modash_validate_printf_v_target "$1"
        elif [[ $1 == -v* ]]; then
          __modash_validate_printf_v_target "${{1#-v}}"
        fi
        shift
      done
      return
      ;;
    mapfile|readarray)
      shift
      while (( $# )); do
        [[ $1 == -C* ]] && __modash_abort "runtime replay cannot allow dynamic mapfile/readarray callback"
        shift
      done
      return
      ;;
    bash|sh|dash|ksh|ksh93|mksh|zsh|ash|busybox)
      ;;
    *)
      shift
      return
      ;;
  esac
  shift
  while (( $# )); do
    if (( skip_next )); then
      skip_next=0
      shift
      continue
    fi
    word=$1
    if (( saw_shell_c )); then
      __modash_word_contains_source_payload "$word" && __modash_abort "runtime replay cannot allow dynamic shell source payload"
      saw_shell_c=0
      shift
      continue
    fi
    case "$word" in
      -c|-[!-]*c*)
        saw_shell_c=1
        ;;
      -O|+O|-o|+o)
        skip_next=1
        ;;
    esac
    shift
  done
}}

__modash_validate_printf_v_target() {{
  local target=$1
  [[ $target =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || __modash_abort "runtime replay cannot allow dynamic printf -v target"
  [[ $target != __modash_* ]] || __modash_abort "runtime replay cannot allow dynamic printf -v target"
}}

__modash_guard_dynamic_command_preserve_status() {{
  local prior_status=$?
  __modash_guard_dynamic_command "$@"
  ( exit "$prior_status" )
}}

declare -a __modash_edge_keys=({" ".join(shlex.quote(key) for key in edge_keys)})
declare -a __modash_process_keys=({" ".join(shlex.quote(key) for key in process_keys)})
declare -A __modash_edge_target=()
declare -A __modash_edge_resolved_path=()
declare -A __modash_edge_kind=()
declare -A __modash_edge_source_entry_status=()
declare -A __modash_edge_status=()
declare -A __modash_edge_argc=()
declare -A __modash_edge_arg=()
declare -A __modash_edge_diag_file=()
declare -A __modash_edge_diag_line=()
declare -A __modash_edge_diag_message=()
declare -A __modash_edge_seen=()
declare -A __modash_edge_consumed=()
declare -A __modash_process_expected=()
declare -A __modash_process_seen=()
declare -A __modash_process_consumed=()
__modash_replay_kind=
__modash_replay_resolved_path=
__modash_replay_source_entry_status=0
__modash_replay_status=0
__modash_replay_argc=0
__modash_replay_args=()
__modash_replay_diag_file=
__modash_replay_diag_line=
__modash_replay_diag_message=
__modash_replay_target=
__modash_replay_select_active=0
__modash_verify_trap_active=0

{chr(10).join(map_setup)}
{chr(10).join(f"__modash_process_expected[{shlex.quote(key)}]=1" for key in process_keys)}
readonly -a __modash_edge_keys __modash_process_keys
readonly -A __modash_edge_target __modash_edge_resolved_path __modash_edge_kind __modash_edge_source_entry_status __modash_edge_status __modash_edge_argc __modash_edge_arg
readonly -A __modash_edge_diag_file __modash_edge_diag_line __modash_edge_diag_message __modash_process_expected

__modash_resolve_source_path() {{
  local source_path=${{1-}} directory old_ifs cwd
  cwd=$(__modash_physical_pwd)
  if [[ -z $source_path ]]; then
    builtin printf '%s/' "$cwd"
    return
  fi
  if [[ $source_path == */* ]]; then
    if [[ $source_path == /* ]]; then
      builtin printf '%s' "$source_path"
    else
      builtin printf '%s/%s' "$cwd" "$source_path"
    fi
    return
  fi
  if ! builtin shopt -q sourcepath; then
    builtin printf '%s/%s' "$cwd" "$source_path"
    return
  fi
  old_ifs=$IFS
  IFS=:
  for directory in $PATH; do
    if [[ -z $directory ]]; then
      directory=.
    fi
    if [[ -f $directory/$source_path ]]; then
      if [[ $directory == /* ]]; then
        builtin printf '%s/%s' "$directory" "$source_path"
      else
        builtin printf '%s/%s/%s' "$cwd" "$directory" "$source_path"
      fi
      IFS=$old_ifs
      return
    fi
  done
  IFS=$old_ifs
  builtin printf '%s/%s' "$cwd" "$source_path"
}}

__modash_normalize_source_path() {{
  local path=${{1-}} directory basename
  if [[ -z $path ]]; then
    builtin printf ''
    return
  fi
  directory=${{path%/*}}
  basename=${{path##*/}}
  if [[ $directory == "$path" ]]; then
    directory=$(__modash_physical_pwd)
  elif [[ -z $directory ]]; then
    directory=/
  fi
  if [[ -d $directory ]]; then
    ( builtin cd -P -- "$directory" && builtin printf '%s/%s' "$PWD" "$basename" )
    return
  fi
  builtin printf '%s' "$path"
}}

__modash_select_source_edge() {{
  local base=$1 seen key argc index arg_key
  [[ $__modash_replay_select_active == 1 ]] || __modash_abort "generated source selector called outside replay group"
  __modash_replay_kind=
  __modash_replay_resolved_path=
  __modash_replay_source_entry_status=0
  __modash_replay_status=0
  __modash_replay_argc=0
  __modash_replay_args=()
  __modash_replay_diag_file=
  __modash_replay_diag_line=
  __modash_replay_diag_message=
  __modash_replay_target=
  seen=${{__modash_edge_seen[$base]:-0}}
  key="${{base}}|${{seen}}"
  if [[ -z ${{__modash_edge_kind[$key]+set}} ]]; then
    __modash_abort "unobserved or over-consumed source edge: $key"
  fi
  __modash_edge_seen[$base]=$((seen + 1))
  __modash_edge_consumed[$key]=1
  __modash_replay_kind=${{__modash_edge_kind[$key]}}
  __modash_replay_resolved_path=${{__modash_edge_resolved_path[$key]}}
  __modash_replay_source_entry_status=${{__modash_edge_source_entry_status[$key]:-0}}
  __modash_replay_status=${{__modash_edge_status[$key]:-0}}
  __modash_replay_target=${{__modash_edge_target[$key]}}
  __modash_replay_diag_file=${{__modash_edge_diag_file[$key]:-}}
  __modash_replay_diag_line=${{__modash_edge_diag_line[$key]:-}}
  __modash_replay_diag_message=${{__modash_edge_diag_message[$key]:-}}
  argc=${{__modash_edge_argc[$key]:-0}}
  __modash_replay_argc=$argc
  for ((index = 0; index < argc; index++)); do
    arg_key="${{key}}"$'\x1f'"${{index}}"
    __modash_replay_args+=("${{__modash_edge_arg[$arg_key]}}")
  done
}}

__modash_validate_source_argv() {{
  local expansion_status=$1 source_path actual_resolved expected_arg actual_arg index
  shift
  if (( expansion_status != __modash_replay_source_entry_status )); then
    __modash_abort "observed source argument status drift"
  fi
  if (( $# == 0 )); then
    source_path=
  else
    source_path=$1
  fi
  actual_resolved=$(__modash_normalize_source_path "$(__modash_resolve_source_path "$source_path")")
  if [[ $actual_resolved != "$__modash_replay_resolved_path" ]]; then
    if [[ $__modash_replay_kind != file || ! -e $actual_resolved || ! -e $__modash_replay_resolved_path || ! $actual_resolved -ef $__modash_replay_resolved_path ]]; then
      __modash_abort "observed source path drift"
    fi
  fi
  if [[ $__modash_replay_kind == missing && -n $source_path && ( -e $actual_resolved || -L $actual_resolved ) ]]; then
    __modash_abort "observed missing source drift"
  fi
  if (( $# != __modash_replay_argc + 1 )); then
    __modash_abort "observed source argument drift"
  fi
  shift
  for ((index = 0; index < __modash_replay_argc; index++)); do
    expected_arg=${{__modash_replay_args[$index]}}
    actual_arg=${{1-}}
    if [[ $actual_arg != "$expected_arg" ]]; then
      __modash_abort "observed source argument drift"
    fi
    shift
  done
}}

__modash_validate_source_argv_masked() {{
  local expansion_status=$1 skip_mask=$2 source_path actual_resolved expected_arg actual_arg index
  shift 2
  if (( expansion_status != __modash_replay_source_entry_status )); then
    __modash_abort "observed source argument status drift"
  fi
  if (( $# == 0 )); then
    source_path=
  else
    source_path=$1
  fi
  actual_resolved=$(__modash_normalize_source_path "$(__modash_resolve_source_path "$source_path")")
  if [[ $actual_resolved != "$__modash_replay_resolved_path" ]]; then
    if [[ $__modash_replay_kind != file || ! -e $actual_resolved || ! -e $__modash_replay_resolved_path || ! $actual_resolved -ef $__modash_replay_resolved_path ]]; then
      __modash_abort "observed source path drift"
    fi
  fi
  if [[ $__modash_replay_kind == missing && -n $source_path && ( -e $actual_resolved || -L $actual_resolved ) ]]; then
    __modash_abort "observed missing source drift"
  fi
  if (( $# != __modash_replay_argc + 1 )); then
    __modash_abort "observed source argument drift"
  fi
  shift
  for ((index = 0; index < __modash_replay_argc; index++)); do
    expected_arg=${{__modash_replay_args[$index]}}
    actual_arg=${{1-}}
    if [[ $skip_mask != *":$index:"* && $actual_arg != "$expected_arg" ]]; then
      __modash_abort "observed source argument drift"
    fi
    shift
  done
}}

__modash_validate_source_path_and_argc() {{
  local expansion_status=$1 expected_argc=$2 source_path actual_resolved
  shift 2
  if (( expansion_status != __modash_replay_source_entry_status )); then
    __modash_abort "observed source argument status drift"
  fi
  if (( $# == 0 )); then
    source_path=
  else
    source_path=$1
  fi
  actual_resolved=$(__modash_normalize_source_path "$(__modash_resolve_source_path "$source_path")")
  if [[ $actual_resolved != "$__modash_replay_resolved_path" ]]; then
    if [[ $__modash_replay_kind != file || ! -e $actual_resolved || ! -e $__modash_replay_resolved_path || ! $actual_resolved -ef $__modash_replay_resolved_path ]]; then
      __modash_abort "observed source path drift"
    fi
  fi
  if [[ $__modash_replay_kind == missing && -n $source_path && ( -e $actual_resolved || -L $actual_resolved ) ]]; then
    __modash_abort "observed missing source drift"
  fi
  if (( __modash_replay_argc != expected_argc )); then
    __modash_abort "observed source argument drift"
  fi
}}

source() {{
  __modash_abort "unobserved live source command: source"
}}

.() {{
  __modash_abort "unobserved live source command: ."
}}

exec() {{
  __modash_abort "runtime replay cannot allow live exec"
}}

trap() {{
  __modash_abort "runtime replay cannot allow live trap"
}}

kill() {{
  local arg after_double_dash=0 skip_next=0 signal_seen=0
  for arg in "$@"; do
    if (( skip_next )); then
      skip_next=0
      continue
    fi
    if (( ! after_double_dash )); then
      case "$arg" in
        --)
          after_double_dash=1
          continue
          ;;
        -s|-n)
          skip_next=1
          signal_seen=1
          continue
          ;;
        -[A-Za-z]*)
          signal_seen=1
          continue
          ;;
        -[0-9]*)
          if (( signal_seen )); then
            __modash_abort "runtime replay cannot allow kill target: $arg"
          fi
          signal_seen=1
          continue
          ;;
      esac
    fi
    case "$arg" in
      "$$"|"$BASHPID"|0|-*)
        __modash_abort "runtime replay cannot allow kill target: $arg"
        ;;
    esac
    if [[ $arg =~ ^[0-9]+$ ]] && (( arg == $$ || arg == BASHPID )); then
      __modash_abort "runtime replay cannot allow kill target: $arg"
    fi
  done
  "$__modash_kill" "$@"
}}

__modash_select_child_process() {{
  local process_index=$1 seen key
  [[ $__modash_replay_select_active == 1 ]] || __modash_abort "generated child selector called outside replay group"
  seen=${{__modash_process_seen[$process_index]:-0}}
  key="${{process_index}}|${{seen}}"
  if [[ -z ${{__modash_process_expected[$key]+set}} ]]; then
    __modash_abort "unobserved or over-consumed child process: $key"
  fi
  __modash_process_seen[$process_index]=$((seen + 1))
  __modash_process_consumed[$key]=1
}}

__modash_reject_function_override() {{
  local name=$1
  if declare -F "$name" >/dev/null; then
    __modash_abort "observed child process wrapper was replaced by a shell function: $name"
  fi
}}

__modash_verify_replay_consumed() {{
  local status=${{1:-$?}} key
  [[ $__modash_verify_trap_active == 1 ]] || __modash_abort "generated replay verifier called outside EXIT trap"
  if [[ -s "$__modash_tmp/replay-failure" ]]; then
    status={REPLAY_FAILURE_STATUS}
  fi
{edge_verify}
{process_verify}
  if [[ -n ${{__modash_child_replay_marker:-}} ]]; then
    builtin printf '%s\\n' "${{__modash_child_replay_token:-}}" > "$__modash_child_replay_marker" || builtin exit {REPLAY_FAILURE_STATUS}
  fi
  "$__modash_rm" -rf -- "$__modash_tmp"
  builtin trap - EXIT
  builtin exit "$status"
}}

builtin trap '__modash_trap_status=$?; __modash_verify_trap_active=1; __modash_verify_replay_consumed "$__modash_trap_status"' EXIT
set +p
'''


def _required_tool(name: str) -> str:
    path = shutil.which(name)
    if path is None:
        raise RuntimeObservedCompileError(
            f"runtime graph compiler cannot locate required replay tool: {name}",
            code="runtime.compile.tool_unavailable",
        )
    try:
        resolved = Path(path).resolve(strict=True)
    except OSError as exc:
        raise RuntimeObservedCompileError(
            f"runtime graph compiler cannot resolve required replay tool: {name}: {path}",
            code="runtime.compile.tool_unavailable",
        ) from exc
    if not resolved.is_absolute():
        raise RuntimeObservedCompileError(
            f"runtime graph compiler resolved non-absolute replay tool path: {name}: {resolved}",
            code="runtime.compile.tool_unavailable",
        )
    return str(resolved)


def _environment_verify_lines(environment_values: dict[str, str]) -> list[str]:
    lines: list[str] = []
    for key, value in sorted(environment_values.items()):
        if not _is_shell_identifier(key):
            continue
        lines.extend([
            f"if [[ ${{{key}+x}} != x || ${{{key}}} != {shlex.quote(value)} ]]; then",
            f"  __modash_abort {shlex.quote('observed environment drift: ' + key)}",
            "fi",
        ])
    return lines


def _is_shell_identifier(value: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", value))


def _edge_map_lines(base_id: str, occurrence: int, edge: _ReplayEdge, target_logical_paths: dict[str, str]) -> list[str]:
    key = f"{base_id}|{occurrence}"
    lines = [
        f"__modash_edge_kind[{shlex.quote(key)}]={shlex.quote('file' if edge.is_file else 'missing')}",
        f"__modash_edge_resolved_path[{shlex.quote(key)}]={shlex.quote(edge.resolved_path)}",
        f"__modash_edge_source_entry_status[{shlex.quote(key)}]={edge.source_entry_status}",
        f"__modash_edge_status[{shlex.quote(key)}]={edge.status}",
        f"__modash_edge_argc[{shlex.quote(key)}]={len(edge.arguments)}",
    ]
    if edge.is_file:
        try:
            target = target_logical_paths[edge.resolved_path]
        except KeyError as exc:
            raise RuntimeObservedCompileError(
                f"observed source target is not bundled: {edge.resolved_path}",
                code="runtime.compile.unbundled_target",
            ) from exc
        lines.append(f"__modash_edge_target[{shlex.quote(key)}]={shlex.quote(target)}")
    else:
        lines.extend([
            f"__modash_edge_target[{shlex.quote(key)}]=''",
            f"__modash_edge_diag_file[{shlex.quote(key)}]={shlex.quote(edge.site_file)}",
            f"__modash_edge_diag_line[{shlex.quote(key)}]={edge.site_line}",
            f"__modash_edge_diag_message[{shlex.quote(key)}]={shlex.quote(_missing_source_message(edge))}",
        ])
    for index, argument in enumerate(edge.arguments):
        arg_key = f"{key}\x1f{index}"
        lines.append(f"__modash_edge_arg[{shlex.quote(arg_key)}]={shlex.quote(argument)}")
    return lines

def _target_logical_paths(file_units: dict[str, _RewriteUnit]) -> dict[str, str]:
    return {
        str(Path(unit.physical_path).resolve(strict=False)): logical_path
        for logical_path, unit in file_units.items()
        if unit.physical_path is not None and logical_path != ENTRYPOINT_LOGICAL_PATH
    }

def _verify_consumed_lines(array_name: str, label: str, keys: list[str]) -> list[str]:
    lines: list[str] = []
    for key in keys:
        quoted_key = shlex.quote(key)
        lines.extend([
            f"  if [[ -z ${{{array_name}[{quoted_key}]+set}} ]]; then",
            f"    builtin printf 'modash runtime replay error: unconsumed observed {label}: %s\\n' {quoted_key} >&2",
            '    "$__modash_rm" -rf -- "$__modash_tmp"',
            "    builtin trap - EXIT",
            f"    builtin exit {REPLAY_FAILURE_STATUS}",
            "  fi",
        ])
    return lines

def _missing_source_message(edge: _ReplayEdge) -> str:
    value = edge.source_value
    if edge.status == 2 and not value:
        command_name = _missing_source_command_name(edge)
        return f"{command_name}: filename argument required"
    return f"{value}: No such file or directory"

def _missing_source_command_name(edge: _ReplayEdge) -> str:
    invocation = source_command_invocation(_first_source_segment(edge.xtrace_command) or "")
    return invocation.command_name if invocation is not None else "source"
