from __future__ import annotations

import base64
import shlex
from pathlib import Path

from methods.compile import SET_SHEBANG
from methods.runtime_evaluator.compiler_model import (
    ENTRYPOINT_LOGICAL_PATH,
    REPLAY_FAILURE_STATUS,
    RuntimeObservedCompileError,
    _EmbeddedFile,
    _ReplayEdge,
    _RewriteUnit,
    _validate_logical_path,
)
from methods.source_commands import source_command_invocation

def _render_replay_prelude(
    embedded_files: tuple[_EmbeddedFile, ...],
    assignments: dict[str, list[_ReplayEdge]],
    target_logical_paths: dict[str, str],
) -> str:
    file_setup = []
    for file in embedded_files:
        _validate_logical_path(file.logical_path)
        encoded = base64.b64encode(file.content.encode("utf-8")).decode("ascii")
        file_setup.append("__modash_write_embedded_file " f"{shlex.quote(file.logical_path)} {shlex.quote(encoded)}")

    map_setup: list[str] = []
    edge_keys: list[str] = []
    for base_id, edges in sorted(assignments.items()):
        for occurrence, edge in enumerate(edges):
            key = f"{base_id}|{occurrence}"
            edge_keys.append(key)
            map_setup.extend(_edge_map_lines(base_id, occurrence, edge, target_logical_paths))

    return f'''{SET_SHEBANG}
# Generated by modash 0.7 trusted runtime graph compiler.

__modash_tmp=$(mktemp -d "${{TMPDIR:-/tmp}}/modash-runtime.XXXXXX") || exit {REPLAY_FAILURE_STATUS}
__modash_aborting=0

__modash_abort() {{
  __modash_aborting=1
  printf 'modash runtime replay error: %s\\n' "$1" >&2
  exit {REPLAY_FAILURE_STATUS}
}}

__modash_write_embedded_file() {{
  local logical_path=$1 encoded=$2 output_path
  output_path="$__modash_tmp/$logical_path"
  mkdir -p "$(dirname -- "$output_path")" || __modash_abort "could not create embedded file directory: $logical_path"
  printf '%s' "$encoded" | base64 -d > "$output_path" || __modash_abort "could not unpack embedded file: $logical_path"
}}

{chr(10).join(file_setup)}

declare -a __modash_edge_keys=({" ".join(shlex.quote(key) for key in edge_keys)})
declare -A __modash_edge_target=()
declare -A __modash_edge_kind=()
declare -A __modash_edge_status=()
declare -A __modash_edge_argc=()
declare -A __modash_edge_arg=()
declare -A __modash_edge_diag_file=()
declare -A __modash_edge_diag_line=()
declare -A __modash_edge_diag_message=()
declare -A __modash_edge_seen=()
declare -A __modash_edge_consumed=()
__modash_replay_file=
__modash_replay_kind=
__modash_replay_status=0
__modash_replay_args=()
__modash_replay_diag_file=
__modash_replay_diag_line=
__modash_replay_diag_message=

{chr(10).join(map_setup)}

__modash_select_source_edge() {{
  local base=$1 seen key argc index arg_key
  __modash_replay_file=
  __modash_replay_kind=
  __modash_replay_status=0
  __modash_replay_args=()
  __modash_replay_diag_file=
  __modash_replay_diag_line=
  __modash_replay_diag_message=
  seen=${{__modash_edge_seen[$base]:-0}}
  key="${{base}}|${{seen}}"
  if [[ -z ${{__modash_edge_kind[$key]+set}} ]]; then
    __modash_abort "unobserved or over-consumed source edge: $key"
  fi
  __modash_edge_seen[$base]=$((seen + 1))
  __modash_edge_consumed[$key]=1
  __modash_replay_kind=${{__modash_edge_kind[$key]}}
  __modash_replay_status=${{__modash_edge_status[$key]:-0}}
  __modash_replay_file="$__modash_tmp/${{__modash_edge_target[$key]}}"
  __modash_replay_diag_file=${{__modash_edge_diag_file[$key]:-}}
  __modash_replay_diag_line=${{__modash_edge_diag_line[$key]:-}}
  __modash_replay_diag_message=${{__modash_edge_diag_message[$key]:-}}
  argc=${{__modash_edge_argc[$key]:-0}}
  for ((index = 0; index < argc; index++)); do
    arg_key="${{key}}"$'\x1f'"${{index}}"
    __modash_replay_args+=("${{__modash_edge_arg[$arg_key]}}")
  done
}}

__modash_verify_replay_consumed() {{
  local status=$? key
  if ((__modash_aborting)); then
    rm -rf -- "$__modash_tmp"
    exit "$status"
  fi
  for key in "${{__modash_edge_keys[@]}}"; do
    if [[ -z ${{__modash_edge_consumed[$key]+set}} ]]; then
      printf 'modash runtime replay error: unconsumed observed source edge: %s\\n' "$key" >&2
      rm -rf -- "$__modash_tmp"
      exit {REPLAY_FAILURE_STATUS}
    fi
  done
  rm -rf -- "$__modash_tmp"
  exit "$status"
}}

trap '__modash_verify_replay_consumed' EXIT
'''

def _edge_map_lines(base_id: str, occurrence: int, edge: _ReplayEdge, target_logical_paths: dict[str, str]) -> list[str]:
    key = f"{base_id}|{occurrence}"
    lines = [
        f"__modash_edge_kind[{shlex.quote(key)}]={shlex.quote('file' if edge.is_file else 'missing')}",
        f"__modash_edge_status[{shlex.quote(key)}]={edge.status}",
        f"__modash_edge_argc[{shlex.quote(key)}]={len(edge.arguments)}",
    ]
    if edge.is_file:
        try:
            target = target_logical_paths[edge.resolved_path]
        except KeyError as exc:
            raise RuntimeObservedCompileError(
                f"observed source target is not bundled: {edge.resolved_path}",
                code="runtime.compile.unbundled_target",
            ) from exc
        lines.append(f"__modash_edge_target[{shlex.quote(key)}]={shlex.quote(target)}")
    else:
        lines.extend([
            f"__modash_edge_target[{shlex.quote(key)}]=''",
            f"__modash_edge_diag_file[{shlex.quote(key)}]={shlex.quote(edge.site_file)}",
            f"__modash_edge_diag_line[{shlex.quote(key)}]={edge.site_line}",
            f"__modash_edge_diag_message[{shlex.quote(key)}]={shlex.quote(_missing_source_message(edge))}",
        ])
    for index, argument in enumerate(edge.arguments):
        arg_key = f"{key}\x1f{index}"
        lines.append(f"__modash_edge_arg[{shlex.quote(arg_key)}]={shlex.quote(argument)}")
    return lines

def _target_logical_paths(file_units: dict[str, _RewriteUnit]) -> dict[str, str]:
    return {
        str(Path(unit.physical_path).resolve(strict=False)): logical_path
        for logical_path, unit in file_units.items()
        if unit.physical_path is not None and logical_path != ENTRYPOINT_LOGICAL_PATH
    }

def _missing_source_message(edge: _ReplayEdge) -> str:
    value = edge.source_value
    if edge.status == 2 and not value:
        command_name = _missing_source_command_name(edge)
        return f"{command_name}: filename argument required"
    return f"{value}: No such file or directory"

def _missing_source_command_name(edge: _ReplayEdge) -> str:
    invocation = source_command_invocation(_first_source_segment(edge.xtrace_command) or "")
    return invocation.command_name if invocation is not None else "source"
